engines:
  rubocop:
    enabled: true
 
    config:
      languages:
      - ruby

ratings:
  paths:
  - "**.rb"

exclude_paths:
  - etc/**/*
  - examples/**/*
  - spec/**/*
7c176accf5194648f727f5defcb9e782281d3d29
 duplication:
    enabled: true
