integration:
  name: minitest

requires:
  - twitter

environment_variables:
  MUTANT: "1"

includes:
  - lib
  - test

usage: opensource

mutation:
  operators: full

matcher:
  subjects:
    - Twitter*
