module Addressable
  class URI
    def self.parse: (untyped uri) -> Addressable::URI
    def self.new: (**untyped) -> Addressable::URI

    def path: () -> String
    def query_values=: (untyped values) -> void
    def query: () -> String?
    def to_s: () -> String
    def to_str: () -> String
  end
end
