# Minimal type stubs for the http gem

module HTTP
  def self.headers: (untyped) -> untyped
  def self.via: (*untyped) -> untyped
  def self.get: (String, **untyped) -> untyped

  module FormData
    def self.create: (untyped, **untyped) -> untyped

    class File
      def initialize: (untyped, **untyped) -> void
    end
  end

  class Request
    def initialize: (**untyped) -> void
  end
end
